package com.oneb.common.ai.openrouter.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a choice in the OpenRouter.ai chat completion response.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Choice {

    /**
     * The index of this choice in the list of choices.
     */
    @JsonProperty("index")
    private Integer index;

    /**
     * The message generated by the model.
     */
    @JsonProperty("message")
    private Message message;

    /**
     * The reason the model stopped generating tokens.
     */
    @JsonProperty("finish_reason")
    private String finishReason;
}
